name: trytwo
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.6 <4.0.0'

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/icon.png

  fonts:
    - family: SixtyFour
      fonts:
        - asset: assets/fonts/SixtyFour.ttf
dependencies:
  google_fonts: ^6.1.0
